import { useMemo, useState } from 'react';
import type { GameClass, Item, ItemCategory, LoadoutEntry } from '../types/game';
import { humanizeRequirement } from '../rules/requirements';

interface Props { title: string; category: ItemCategory; items: Item[]; entries: Array<LoadoutEntry & { item: Item; stackKg: number; stackPrice: number; eligibility: { eligible: boolean; messages: string[]; warnings: string[] } }>; gameClass: GameClass; classes: GameClass[]; onAdd: (id: number) => void; onQuantity: (entryId: string, quantity: number) => void; onRemove: (entryId: string) => void; }
export function LoadoutSection({ title, category, items, entries, gameClass, classes, onAdd, onQuantity, onRemove }: Props) {
  const available = useMemo(() => items.filter(item => item.category === category).sort((a,b) => a.name.localeCompare(b.name)), [items, category]);
  const [selected, setSelected] = useState('');
  return <section className="loadout-section"><div className="section-heading"><h2>{title}</h2><div className="add-row"><select aria-label={`Add ${title}`} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Select {title}</option>{available.map(item => <option key={item.id} value={item.id}>{item.name} · {item.weightKg.toFixed(3)} kg · Price {item.price.toLocaleString()}</option>)}</select><button disabled={!selected} onClick={() => { onAdd(Number(selected)); setSelected(''); }}>Add</button></div></div>
    {entries.length === 0 ? <p className="empty">No {title.toLowerCase()} selected.</p> : <div className="entries">{entries.map(entry => { const rules = humanizeRequirement(entry.item.requirement, classes); return <article className={`entry ${entry.eligibility.eligible ? 'ready' : 'blocked'}`} key={entry.entryId}><div className="entry-name"><strong>{entry.item.name}</strong><span>{entry.item.sourceCategory}</span>{entry.item.description && <small>{entry.item.description}</small>}</div><label>Qty<input aria-label={`Quantity for ${entry.item.name}`} type="number" min="1" value={entry.quantity} onChange={e => onQuantity(entry.entryId, Math.max(1, Number(e.target.value) || 1))}/></label><dl><div><dt>Unit</dt><dd>{entry.item.weightKg.toFixed(3)} kg</dd></div><div><dt>Stack</dt><dd>{entry.stackKg.toFixed(3)} kg</dd></div><div><dt>Unit price</dt><dd>{entry.item.price.toLocaleString()}</dd></div><div><dt>Total price</dt><dd>{entry.stackPrice.toLocaleString()}</dd></div></dl><div className="eligibility"><b>{entry.eligibility.eligible ? 'ELIGIBLE' : 'BLOCKED'}</b>{entry.eligibility.messages.map(m => <span key={m}>{m}</span>)}{rules.map(rule => <span key={rule}>{rule}</span>)}{entry.eligibility.warnings.map(w => <span className="warning" key={w}>{w}</span>)}</div><button className="remove" onClick={() => onRemove(entry.entryId)}>Remove</button></article>; })}</div>}
  </section>;
}
