import { readFile, writeFile, stat } from 'node:fs/promises';
import { join } from 'node:path';

const zoneDir = process.env.EOL_ZONE_DATA ?? 'C:/Program Files (x86)/Steam/steamapps/common/FreeInfantry';
const names = ['PioneerStation.itm', 'PioneerStation.veh', 'PioneerStation.rpg', 'PioneerStation_notes.txt'];
const csv = line => { const out=[]; let v='', q=false; for(let i=0;i<line.length;i++){const c=line[i]; if(c==='"'){if(q&&line[i+1]==='"'){v+=c;i++;}else q=!q;}else if(c===','&&!q){out.push(v);v='';}else v+=c;} out.push(v); return out; };
const readRows = async name => (await readFile(join(zoneDir, name), 'utf8')).split(/\r?\n/).filter(Boolean).map(csv);
const attrMap = {12:'strength',13:'vitality',14:'vehicle',15:'deftness',16:'technical',17:'leadership',18:'power',19:'commerce',20:'stamina'};
function requirement(raw='') { const minimumAttributes={}; for(const [, id, value] of raw.matchAll(/-(12|13|14|15|16|17|18|19|20)(\d{2,3})/g)) minimumAttributes[attrMap[id]]=Number(value); const allowed=new Set(), blocked=new Set(); for(const m of raw.matchAll(/(!?)\(?([0-9]+(?:\|[0-9]+)*)\)?/g)){ if(['-','%'].includes(raw[m.index-1])) continue; for(const n of m[2].split('|').map(Number).filter(n=>n>0&&n<100))(m[1]==='!'?blocked:allowed).add(n); } return {rawExpression:raw,allowedClassIds:allowed.size?[...allowed]:undefined,blockedClassIds:blocked.size?[...blocked]:undefined,minimumAttributes,hasUnverifiedGate:/[@#%]/.test(raw)||/[^\d|()!&\-]/.test(raw)}; }
function category(source, name) { if(source.startsWith('Armor-')) return 'armor'; if(source.startsWith('Ammo-')) { if(source === 'Ammo-Regular' && /(9mm|4mm|7\.7mm|12 Gauge|60mm|40mm|70mm)/i.test(name)) return null; return 'ammo'; } if(source.startsWith('Weapons-')) return 'weapons'; if(source.startsWith('Equipment-')) return 'equipment'; if(/^(Items|Consumables|Tools|Misc|Heal\/Repair)/i.test(source)) return 'items'; return null; }
const number = value => Number(value) || 0;
const itm = await readRows('PioneerStation.itm'); const veh = await readRows('PioneerStation.veh'); const rpg = await readRows('PioneerStation.rpg');
const normalizeName = value => value.toLowerCase().replace(/trooper/g,'').replace(/[^a-z0-9]/g,'');
const vehicles = new Map(veh.filter(r=>r[0]==='2').map(r=>[normalizeName(r[3]), {baseHp:number(r[6]),baseCarryKg:number(r[33])}]));
const classes = rpg.filter(r=>/^Classes - /.test(r[40]) && Number(r[1])>0 && !/Unused|Default/.test(r[40]) && vehicles.has(normalizeName(r[39]))).map(r=>({id:number(r[1]),name:r[39],group:r[40].replace('Classes - ',''),...vehicles.get(normalizeName(r[39]))}));
const items = itm.map(r=>{const sourceCategory=r[4]??''; const itemCategory=category(sourceCategory,r[3]??''); if(!itemCategory)return null; const armor=itemCategory==='armor'?{mobilityRaw:[number(r[42]),number(r[43]),number(r[44])],channels:[[number(r[52]),number(r[53])],[number(r[54]),number(r[55])],[number(r[56]),number(r[57])]].map(([ignoreRaw,protectionRaw])=>({ignoreRaw,protectionRaw}))}:undefined; return {id:number(r[2]),name:r[3],category:itemCategory,sourceCategory,description:r[6]??'',weightKg:number(r[7])/1000,requirement:requirement(r[5]),armor,rawFields:r};}).filter(Boolean).filter(item=>item.weightKg>=0);
const files=Object.fromEntries(await Promise.all(names.map(async name=>{const s=await stat(join(zoneDir,name));return [name,s.mtime.toISOString()]})));
const db={source:{importedAt:new Date().toISOString(),files},classes,items};
await writeFile('src/data/generated.ts', `/* Generated by scripts/import-zone.mjs; do not edit. */\nimport type { GameDatabase } from '../types/game';\nexport const gameData: GameDatabase = ${JSON.stringify(db)};\n`);
console.log(`Imported ${classes.length} playable classes and ${items.length} player-carried items from ${zoneDir}`);
