import { useEffect, useMemo, useState } from 'react';
import { gameData } from './data';
import type { AttributeKey, Loadout } from './types/game';
import { calculateBuild, EMPTY_ATTRIBUTES } from './rules/build';
import { LoadoutSection } from './components/LoadoutSection';
import { ArmorAnalysis } from './components/ArmorAnalysis';
import { ExperiencePlanner } from './components/ExperiencePlanner';
import { SavedBuilds, type SavedBuild } from './components/SavedBuilds';
import { BuildSharing } from './components/BuildSharing';
import { BuildComparison } from './components/BuildComparison';
import './styles.css';
import './styles-extra.css';

const categories = [['Items','items'],['Equipment','equipment'],['Armor','armor'],['Weapons / Addons','weapons'],['Ammo','ammo']] as const;
const blank = (): Loadout => ({ classId: gameData.classes.find(c => c.name === 'Jump Trooper')?.id ?? gameData.classes[0].id, attributes: { ...EMPTY_ATTRIBUTES }, entries: [] });
const attributeLabels: Array<[AttributeKey,string]> = [['deftness','Deftness'],['power','Power'],['stamina','Stamina'],['strength','Strength'],['vitality','Vitality'],['commerce','Commerce'],['leadership','Leadership'],['technical','Technical'],['vehicle','Vehicle']];
export default function App() { const [loadout,setLoadout]=useState<Loadout>(()=>blank()); const [availableXp,setAvailableXp]=useState(0); const [currentAttributes,setCurrentAttributes]=useState({...EMPTY_ATTRIBUTES}); const [saved,setSaved]=useState<SavedBuild[]>(()=>JSON.parse(localStorage.getItem('eol-pioneer-builds')||'[]'));
 useEffect(()=>localStorage.setItem('eol-pioneer-builds',JSON.stringify(saved)),[saved]); const result=useMemo(()=>calculateBuild(loadout,gameData.classes,gameData.items),[loadout]); const gameClass=gameData.classes.find(c=>c.id===loadout.classId)!; const update=<K extends keyof Loadout>(key:K,value:Loadout[K])=>setLoadout(current=>({...current,[key]:value})); const maximumFor=(key:AttributeKey)=>gameData.attributes.find(attribute=>attribute.key===key)?.maxLevel ?? 0; const clampLoadout=(candidate:Loadout):Loadout=>({...candidate,attributes:Object.fromEntries(attributeLabels.map(([key])=>[key,Math.min(maximumFor(key),Math.max(0,candidate.attributes[key]))])) as unknown as Loadout['attributes']}); const classAttributes=Object.entries(gameClass.minimumAttributes) as Array<[AttributeKey,number]>; const missingClassAttributes=classAttributes.filter(([key,required])=>loadout.attributes[key]<required); const classAttributeText=classAttributes.map(([key,required])=>`${attributeLabels.find(([attribute])=>attribute===key)?.[1] ?? key} ${required}`).join(' · ');
 const add=(itemId:number)=>update('entries',[...loadout.entries,{entryId:crypto.randomUUID(),itemId,quantity:1}]); const quantity=(entryId:string,q:number)=>update('entries',loadout.entries.map(e=>e.entryId===entryId?{...e,quantity:q}:e)); const remove=(entryId:string)=>update('entries',loadout.entries.filter(e=>e.entryId!==entryId));
 const save=()=>{const name=window.prompt('Build name');if(name?.trim())setSaved(s=>[...s,{id:crypto.randomUUID(),name:name.trim(),loadout:structuredClone(loadout)}])}; const rename=(b:SavedBuild)=>{const name=window.prompt('Build name',b.name);if(name?.trim())setSaved(s=>s.map(x=>x.id===b.id?{...x,name:name.trim()}:x))};
 return <main><header className="command-deck"><div className="command-brand"><div className="command-mark" aria-hidden="true"><span>IO</span></div><div><p className="eyebrow">EOL PIONEER STATION · LOADOUT CONSOLE</p><h1>{gameClass.name} <span>|</span> HP {result.finalHp} <span>|</span> <em className={result.remainingKg<0?'red':''}>{result.loadKg.toFixed(3)} / {result.maxCarryKg.toFixed(2)} kg</em> <span>|</span> {result.remainingKg.toFixed(3)} kg remaining</h1><p className="source">Zone data imported {new Date(gameData.source.importedAt).toLocaleString()} · source files last changed {Object.values(gameData.source.files)[0]?.slice(0,10)}</p></div></div><div className="command-controls"><div className="console-status"><span><i />SYSTEM LINK: ACTIVE</span><span>PIONEER / LOADOUT</span></div><div className="build-actions"><BuildSharing loadout={loadout} classes={gameData.classes} items={gameData.items} onImport={build=>setSaved(s=>[...s,build])}/><SavedBuilds saved={saved} onSave={save} onLoad={b=>setLoadout(clampLoadout(structuredClone(b.loadout)))} onDuplicate={b=>setSaved(s=>[...s,{...structuredClone(b),id:crypto.randomUUID(),name:`${b.name} copy`}])} onRename={rename} onDelete={b=>setSaved(s=>s.filter(x=>x.id!==b.id))} onReset={()=>setLoadout(blank())}/></div></div></header>
 <section className="setup"><label>Class<span className={availableXp < gameClass.requiredXp ? 'class-xp-gate blocked' : 'class-xp-gate'}>{gameClass.requiredXp ? availableXp < gameClass.requiredXp ? `${(gameClass.requiredXp - availableXp).toLocaleString()} XP needed` : `${gameClass.requiredXp.toLocaleString()} XP requirement met` : 'No XP requirement'}</span>{classAttributeText && <span className={missingClassAttributes.length ? 'class-attribute-gate blocked' : 'class-attribute-gate'}>{missingClassAttributes.length ? `Needs ${missingClassAttributes.map(([key,required])=>`${attributeLabels.find(([attribute])=>attribute===key)?.[1] ?? key} ${required}`).join(' · ')}` : `Attributes: ${classAttributeText}`}</span>}<select value={loadout.classId} onChange={e=>update('classId',Number(e.target.value))}>{gameData.classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.group}{c.requiredXp ? ` · ${c.requiredXp.toLocaleString()} XP` : ''}</option>)}</select></label><div className="attributes">{attributeLabels.map(([key,label])=><label key={key}>{label}<input type="number" min="0" max={maximumFor(key)} value={loadout.attributes[key]} onChange={e=>update('attributes',{...loadout.attributes,[key]:Math.min(maximumFor(key),Math.max(0,Number(e.target.value)||0))})}/></label>)}</div><div className={`weight-meter ${result.remainingKg<0?'overweight':''}`}><span style={{width:`${Math.min(100,result.percentUsed)}%`}}></span><b>{result.percentUsed.toFixed(1)}% carry used</b></div><ExperiencePlanner availableXp={availableXp} current={currentAttributes} target={loadout.attributes} attributes={gameData.attributes} rules={gameData.attributeCostRules} onAvailableXpChange={setAvailableXp} onCurrentChange={(key,value)=>setCurrentAttributes(current=>({...current,[key]:value}))}/></section>
 <BuildComparison current={loadout} saved={saved} classes={gameData.classes} items={gameData.items}/><ArmorAnalysis entries={result.entries}/>{categories.map(([title,category])=><LoadoutSection key={category} title={title} category={category} items={gameData.items} entries={result.entries.filter(e=>e.item.category===category)} gameClass={gameClass} classes={gameData.classes} onAdd={add} onQuantity={quantity} onRemove={remove}/>)}</main>; }
